apiVersion: batch/v1
kind: CronJob
metadata:
  name: riddle-cron
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: riddle-cron
            image: avramstefan/riddle-cron:latest
          restartPolicy: OnFailure
